# Generated by Django 5.1.4 on 2024-12-26 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('campo', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmetrackbd.category')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('need_washing', models.BooleanField()),
                ('need_sterilization', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('need_discard', models.BooleanField()),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmetrackbd.condition')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmetrackbd.material')),
            ],
        ),
        migrations.CreateModel(
            name='Tratament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('washing', models.BooleanField()),
                ('sterilization', models.BooleanField()),
                ('distribution', models.BooleanField()),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('finish_at', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmetrackbd.material')),
            ],
        ),
    ]
